// Generated by view binder compiler. Do not edit!
package com.kylinxin.myweather.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.widget.SearchView;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.kylinxin.myweather.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMoreLocationBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final RelativeLayout editLayout;

  @NonNull
  public final ImageView editLocation;

  @NonNull
  public final ListView locationList;

  @NonNull
  public final SearchView searchView;

  @NonNull
  public final RecyclerView weatherRecycler;

  private ActivityMoreLocationBinding(@NonNull RelativeLayout rootView,
      @NonNull RelativeLayout editLayout, @NonNull ImageView editLocation,
      @NonNull ListView locationList, @NonNull SearchView searchView,
      @NonNull RecyclerView weatherRecycler) {
    this.rootView = rootView;
    this.editLayout = editLayout;
    this.editLocation = editLocation;
    this.locationList = locationList;
    this.searchView = searchView;
    this.weatherRecycler = weatherRecycler;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMoreLocationBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMoreLocationBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_more_location, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMoreLocationBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.editLayout;
      RelativeLayout editLayout = ViewBindings.findChildViewById(rootView, id);
      if (editLayout == null) {
        break missingId;
      }

      id = R.id.editLocation;
      ImageView editLocation = ViewBindings.findChildViewById(rootView, id);
      if (editLocation == null) {
        break missingId;
      }

      id = R.id.locationList;
      ListView locationList = ViewBindings.findChildViewById(rootView, id);
      if (locationList == null) {
        break missingId;
      }

      id = R.id.searchView;
      SearchView searchView = ViewBindings.findChildViewById(rootView, id);
      if (searchView == null) {
        break missingId;
      }

      id = R.id.weatherRecycler;
      RecyclerView weatherRecycler = ViewBindings.findChildViewById(rootView, id);
      if (weatherRecycler == null) {
        break missingId;
      }

      return new ActivityMoreLocationBinding((RelativeLayout) rootView, editLayout, editLocation,
          locationList, searchView, weatherRecycler);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
