// Generated by view binder compiler. Do not edit!
package com.kylinxin.myweather.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.kylinxin.myweather.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RecyclerWeather7dBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView icon7d;

  @NonNull
  public final TextView maxTemp7d;

  @NonNull
  public final TextView minTemp7d;

  @NonNull
  public final TextView time7d;

  private RecyclerWeather7dBinding(@NonNull LinearLayout rootView, @NonNull ImageView icon7d,
      @NonNull TextView maxTemp7d, @NonNull TextView minTemp7d, @NonNull TextView time7d) {
    this.rootView = rootView;
    this.icon7d = icon7d;
    this.maxTemp7d = maxTemp7d;
    this.minTemp7d = minTemp7d;
    this.time7d = time7d;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static RecyclerWeather7dBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RecyclerWeather7dBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.recycler_weather7d, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RecyclerWeather7dBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.icon_7d;
      ImageView icon7d = ViewBindings.findChildViewById(rootView, id);
      if (icon7d == null) {
        break missingId;
      }

      id = R.id.maxTemp_7d;
      TextView maxTemp7d = ViewBindings.findChildViewById(rootView, id);
      if (maxTemp7d == null) {
        break missingId;
      }

      id = R.id.minTemp_7d;
      TextView minTemp7d = ViewBindings.findChildViewById(rootView, id);
      if (minTemp7d == null) {
        break missingId;
      }

      id = R.id.time_7d;
      TextView time7d = ViewBindings.findChildViewById(rootView, id);
      if (time7d == null) {
        break missingId;
      }

      return new RecyclerWeather7dBinding((LinearLayout) rootView, icon7d, maxTemp7d, minTemp7d,
          time7d);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
