// Generated by view binder compiler. Do not edit!
package com.kylinxin.myweather.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.kylinxin.myweather.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class RecyclerWeather24hBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageView icon24h;

  @NonNull
  public final TextView temp24h;

  @NonNull
  public final TextView time24h;

  private RecyclerWeather24hBinding(@NonNull LinearLayout rootView, @NonNull ImageView icon24h,
      @NonNull TextView temp24h, @NonNull TextView time24h) {
    this.rootView = rootView;
    this.icon24h = icon24h;
    this.temp24h = temp24h;
    this.time24h = time24h;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static RecyclerWeather24hBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static RecyclerWeather24hBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.recycler_weather24h, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static RecyclerWeather24hBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.icon_24h;
      ImageView icon24h = ViewBindings.findChildViewById(rootView, id);
      if (icon24h == null) {
        break missingId;
      }

      id = R.id.temp_24h;
      TextView temp24h = ViewBindings.findChildViewById(rootView, id);
      if (temp24h == null) {
        break missingId;
      }

      id = R.id.time_24h;
      TextView time24h = ViewBindings.findChildViewById(rootView, id);
      if (time24h == null) {
        break missingId;
      }

      return new RecyclerWeather24hBinding((LinearLayout) rootView, icon24h, temp24h, time24h);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
